# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e20d0db6e6f02fa7bfc9d5f00a88372d00a91d66b6cf29008ffd6f299876afcb34b503baa02de2659c80d692dd174eeaedb4f9bd36386f3f68c0acf84eae2b

test:
  secret_key_base: 891c3a0c8abd832ec55423b05444037eb56fc8662a28bc61f0c4b953396f0dc5c2ed5c88b9810058bfc15e82a4d570d9a241ec193001dbe698e467402df22a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
